### PR TITLE
Update spacemesh API

### PR DESCRIPTION
**Pull request by fasmat**
Update poet with the latest spacemesh API

### CODE REVIEW

**Comment by fasmat** [comment]
@poszu the unit tests on windows are very unstable. I executed them 4 times and got different errors every time:

- db file is used by another process
- file seeking fails due to EOF
- when asserting the round ID it is already 2 when it should be 1
- after recovery there are no executing rounds when there should be one

I reverted the last merge in this PR, so that we can get a green build again.

**Comment by poszu** [comment]
> @poszu the unit tests on windows are very unstable. I executed them 4 times and got different errors every time:

I am aware of these issues with Mac and Windows. Unfortunately, the tests were written with some timing assumptions in mind and:
- the mac runner is slow,
- time on windows has low res.

> * db file is used by another process

This is caused by asynchronous round teardown. I plan to fix it in #181.

> * file seeking fails due to EOF

This is caused by generating empty proofs (0 leaves) - it happens on Mac as it is slow and the round is ended the moment it starts. I don't have a clear idea of how to fix it. Perhaps an empty proof is a valid one and it should be broadcasted empty instead of trying to build leaves and nodes?

> * when asserting the round ID it is already 2 when it should be 1
> * after recovery there are no executing rounds when there should be one

It's tracked in #185. 

> I reverted the last merge in this PR, so that we can get a green build again.

These issues are not directly related to the PR you revert. Reverting doesn't fix the problem, it will persist, perhaps a little less often though. I'm against reverting it.


I'd rather stop running tests on mac and windows as they are not the platform that Poets will run on. There's no point in supporting them.

**Comment by poszu** [comment]
Why is it needed to update `api` repo now? Poet only uses the Gateway Service and it's unchanged between v1.5.2 and v1.5.3.

**Comment by fasmat** [comment]
> These issues are not directly related to the PR you revert. Reverting doesn't fix the problem, it will persist, perhaps a little less often though. I'm against reverting it.

That might very well be the case but at the moment `develop` has a red build, and the PR I reverted caused it to become red: https://github.com/spacemeshos/poet/actions/runs/3684903021
This blocks other PRs like this one, that's why I reverted it.

> I'd rather stop running tests on mac and windows as they are not the platform that Poets will run on. There's no point in supporting them.

I'm against this. Poet is a dependency (as a library not just as a service) of go-spacemesh. go-spacemesh needs to support all 3 platforms, so poet should also be tested for all three. We can maybe skip some of the tests on mac and windows if they are only needed for the service but not for the functionality that go-spacemesh uses.

I'd rather stop running tests in parallel if this is unstable until the issues listed above (which seem to be already tracked) are resolved. After that they can be enabled again. The PR that introduced the parallel tests was just unlucky to have a single green build, you can try re-running the CI on the PR and it will fail more often then pass - imo the PR should not have been merged at the current state.

> Why is it needed to update api repo now? Poet only uses the Gateway Service and it's unchanged between v1.5.2 and v1.5.3.

I initially thought it is required to update the API to `v1.5.3` because I had poet related issues in the systests related to a PR I'm trying to merge, but the issue isn't Poet; it's unstable tests. Updating the API isn't required at the moment, but it also shouldn't hurt to do so.

**Comment by poszu** [comment]
>>These issues are not directly related to the PR you revert. Reverting doesn't fix the problem, it will persist, perhaps a little less often though. I'm against reverting it.
>
>That might very well be the case but at the moment develop has a red build, and the PR I reverted caused it to become red: https://github.com/spacemeshos/poet/actions/runs/3684903021
This blocks other PRs like this one, that's why I reverted it.

Again, the failures are not caused by running tests in parallel. Tests are flaky nevertheless and the build will continue to fail even after it's reverted. Running tests in parallel is not unstable. The tests are unstable in general.


>> I'd rather stop running tests on mac and windows as they are not the platform that Poets will run on. There's no point in supporting them.
> 
> I'm against this. Poet is a dependency (as a library not just as a service) of go-spacemesh. go-spacemesh needs to support all 3 platforms, so poet should also be tested for all three. We can maybe skip some of the tests on mac and windows if they are only needed for the service but not for the functionality that go-spacemesh uses.

IMHO, the Poet should not be a dependency of go-spacemesh as a whole or even at all. It's used in two places only:
- unit tests use the integration harness. The poet could (and I think it should) be instead run in a docker container. Alternatively, integration tests could be left for systests.
- to verify proof validity using `verifier.Validate()`. I think that this could be inlined in the go-spacemesh repo. If we were to run tests on mac and win selectively, then only these tests need to be run: poet/verifier/verifier_test.go.

**Comment by fasmat** [comment]
> Again, the failures are not caused by running tests in parallel. Tests are flaky nevertheless and the build will continue to fail even after it's reverted. Running tests in parallel is not unstable. The tests are unstable in general.

Yes, but running them in parallel causes them more often to fail. The build is red, reverting the PR makes the build green. Shall we now not merge any PRs until the issues are resolved?

> IMHO, the Poet should not be a dependency of go-spacemesh as a whole or even at all. It's used in two places only:

This is not the case yet; poet is used on all 3 platforms at the moment. Removing the tests is better than leaving them and just making it less likely that they randomly fail?

**Comment by poszu** [comment]
> The build is red, reverting the PR makes the build green.

IMO it was luck.

**Review by poszu — APPROVED** [review]

**Pull request merged**
